name: Wispbyte Auto Restart

on:
  schedule:
    - cron: '20 3 */5 * *'  # 每 5 天在 UTC 时间 03:20 执行一次
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install seleniumbase requests

      - name: Install WARP
        run: |
          wget https://raw.githubusercontent.com/fscarmen/warp-on-actions/main/warp.sh -O warp.sh
          bash warp.sh

      - name: Run Python script
        env:
          USERNAMES: ${{ secrets.USERNAMES }}
          PASSWORDS: ${{ secrets.PASSWORDS }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python main.py

      - name: Upload Artifacts on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshots
          path: "*.png"
